apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "druid.name" . }}-druid-historical-conf
  labels:
    {{- include "historical.labels" . | indent 4 }}
  annotations:
    {{- include "historical.annotations" . | indent 4 }}
data:
  "log4j2.xml":
    {{- .Files.Get "common/log4j2.xml" | toYaml | indent 4 }}
  "jvm.config":
    {{- if .Values.historical.jvm }}
    {{- printf "%s\n%s" (.Files.Get "common/jvm.config") .Values.historical.jvm | toYaml | indent 4 }}
    {{- else}}
    {{- .Files.Get "common/jvm.config" | toYaml | indent 4 }}
    {{- end }}
  "runtime.properties":
    {{- toYaml .Values.historical.runtime | indent 4 }}
