apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "druid.name" . }}-druid-sa-rolebinding
  labels:
    {{- include "common.labels" . | indent 4 }}
  annotations:
    {{- include "common.annotations" . | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "druid.name" . }}-druid-sa
    apiGroup: ""
roleRef:
  kind: Role
  name: {{ include "druid.name" . }}-druid-sa-role
  apiGroup: rbac.authorization.k8s.io
