apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "druid.name" . }}-druid-secretprovider
  labels:
    {{- include "common.labels" . | indent 4 }}
  annotations:
    {{- include "common.annotations" . | indent 4 }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ include "druid.name" . }}-druid-metadata"
        objectType: "secretsmanager"
        jmesPath:
        - path: "username"
          objectAlias: "'metadata-username'"
        - path: "password"
          objectAlias: "'metadata-password'"
        - path: "host"
          objectAlias: "'metadata-host'"
        - path: "dbname"
          objectAlias: "'metadata-dbname'"
      - objectName: "{{ include "druid.name" . }}-druid-admin"
        objectType: "secretsmanager"
        jmesPath:
        - path: "username"
          objectAlias: "'admin-username'"
        - path: "password"
          objectAlias: "'admin-password'"
      - objectName: "{{ include "druid.name" . }}-druid-system"
        objectType: "secretsmanager"
        jmesPath:
        - path: "username"
          objectAlias: "'system-username'"
        - path: "password"
          objectAlias: "'system-password'"
  secretObjects:
    - secretName: "{{ include "druid.name" . }}-druid-metadata"
      type: "Opaque"
      data:
        - key: "username"
          objectName: "'metadata-username'"
        - key: "password"
          objectName: "'metadata-password'"
        - key: "host"
          objectName: "'metadata-host'"
        - key: "dbname"
          objectName: "'metadata-dbname'"
    - secretName: "{{ include "druid.name" . }}-druid-admin"
      type: "Opaque"
      data:
        - key: "username"
          objectName: "'admin-username'"
        - key: "password"
          objectName: "'admin-password'"
    - secretName: "{{ include "druid.name" . }}-druid-system"
      type: "Opaque"
      data:
        - key: "username"
          objectName: "'system-username'"
        - key: "password"
          objectName: "'system-password'"
